CREATE DATABASE Dreamliner;

CREATE TABLE Guild (
    guildId VARCHAR (100) NOT NULL PRIMARY KEY,
    prefix VARCHAR (10) DEFAULT '>',
    mode VARCHAR (10) DEFAULT 1,
    nsfw BOOLEAN DEFAULT False
);

CREATE TABLE Bans (
   guildId VARCHAR (100) NOT NULL PRIMARY KEY,
   userId VARCHAR (100) NOT NULL,
   removePunish VARCHAR (5000) NOT NULL 
);

CREATE TABLE Mutes (
   guildId VARCHAR (100) NOT NULL PRIMARY KEY,
   userId VARCHAR (100) NOT NULL,
   removePunish VARCHAR (5000) NOT NULL 
);